CREATE TABLE "shortUrl"(
  "id" BIGSERIAL PRIMARY KEY,
  "userId" INTEGER REFERENCES "users"("id"),
  "url" TEXT NOT NULL,
  "shortUrl" TEXT NOT NULL,
  "visitCount" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATE NOT NULL DEFAULT CURRENT_DATE
);